'use strict';

const crypto = require('crypto');

const SCRIPT_NAME = 'hilux-panel';

// Generates the panel script deployed onto a Shelly Wall Display: virtual
// components (toggle + brightness + colour sliders) drive a group of HiluX
// lights, and the reference light's state is mirrored back by polling.
//
// Wall Display quirks this script accounts for (fw 2.7.4):
// - status events arrive aggregated under component "shelly:0" with the
//   per-component values nested inside delta
// - the lights reject transition_duration < 0.5 s
// - the HTTP client methods are "HTTP.Get"/"HTTP.Post" (not HTTP.GET)
function generate({ lights, fade, ids }) {
  const body = `let LIGHTS = ${JSON.stringify(lights)};
let REF = LIGHTS[0];
let SW_ID = ${ids.sw}, BR_ID = ${ids.br}, CT_ID = ${ids.ct};
let SW = "boolean:${ids.sw}", BR = "number:${ids.br}", CT = "number:${ids.ct}";
let FADE = ${JSON.stringify(fade)};
let L = { on: null, b: 50, ct: 3150 };
let holdPolls = 0; // sync pushes suppressed right after we command the lights

function call(url) {
  try { Shelly.call("HTTP.Get", { url: url, timeout: 2 }, function () {}); } catch (e) {}
}
function callAll(qs) {
  holdPolls = 2;
  for (let i = 0; i < LIGHTS.length; i++) call("http://" + LIGHTS[i] + "/rpc/CCT.Set?id=0&" + qs);
}

// Panel interactions -> lights. Events our own sync produces are filtered
// out because the cache is updated before the virtual component is set.
// Value changes only ever act after the first sync has seeded the cache.
function handleVals(vals) {
  if (L.on === null) return;
  if (vals.sw !== undefined && vals.sw !== L.on) {
    L.on = vals.sw;
    if (L.on) callAll("on=true&brightness=" + JSON.stringify(L.b) + "&ct=" + JSON.stringify(L.ct) + "&transition_duration=" + JSON.stringify(FADE));
    else callAll("on=false&transition_duration=" + JSON.stringify(FADE));
  }
  if (vals.b !== undefined) {
    let v = Math.round(vals.b);
    if (v !== L.b) {
      L.b = v;
      L.on = true; // moving the slider implies wanting light
      callAll("on=true&brightness=" + JSON.stringify(v) + "&transition_duration=0.5");
    }
  }
  if (vals.ct !== undefined) {
    let v = Math.round(vals.ct);
    if (v !== L.ct) {
      L.ct = v;
      callAll("ct=" + JSON.stringify(v) + "&transition_duration=0.5");
    }
  }
}

Shelly.addStatusHandler(function (ev) {
  if (!ev || !ev.delta) return;
  let d = ev.delta;
  let vals = {};
  if (ev.component === SW && typeof d.value === "boolean") vals.sw = d.value;
  if (ev.component === BR && typeof d.value === "number") vals.b = d.value;
  if (ev.component === CT && typeof d.value === "number") vals.ct = d.value;
  if (d[SW] && typeof d[SW].value === "boolean") vals.sw = d[SW].value;
  if (d[BR] && typeof d[BR].value === "number") vals.b = d[BR].value;
  if (d[CT] && typeof d[CT].value === "number") vals.ct = d[CT].value;
  handleVals(vals);
});

// Lights -> panel: poll the reference light so changes made elsewhere
// (wall buttons, Homey, wake-up light) show up on the display.
Timer.set(3000, true, function () {
  try {
    Shelly.call("HTTP.Get", { url: "http://" + REF + "/rpc/CCT.GetStatus?id=0", timeout: 2 }, function (res) {
      if (!res || res.code !== 200) return;
      if (holdPolls > 0) { holdPolls--; return; }
      let st = JSON.parse(res.body);
      if (!st) return;
      let first = L.on === null;
      let on = st.output === true;
      let b = typeof st.brightness === "number" ? Math.round(st.brightness) : L.b;
      let ct = typeof st.ct === "number" ? Math.round(st.ct) : L.ct;
      if (first || L.on !== on) { L.on = on; Shelly.call("Boolean.Set", { id: SW_ID, value: on }); }
      if (first || L.b !== b) { L.b = b; Shelly.call("Number.Set", { id: BR_ID, value: b }); }
      if (first || L.ct !== ct) { L.ct = ct; Shelly.call("Number.Set", { id: CT_ID, value: ct }); }
    });
  } catch (e) {}
});
`;

  const hash = crypto.createHash('sha1').update(body).digest('hex').slice(0, 12);
  const code = `// AUTO-GENERATED by the HiluX DS8 Homey app — do not edit by hand.
// Changes are overwritten; configure via the group device in Homey.
// hash:${hash}
${body}`;

  return { code, hash };
}

module.exports = { generate, SCRIPT_NAME };
